<?php
namespace SmsSender\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-05 at 11:36:21.
 */
class CiscoGatewayTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CiscoGateway
     */
    protected $object;
    
    private $messageText = "Message content with ĄŻŹĆŚĘŁÓŃążźćśęłóń";
    
    private $phoneNos = [
        '48123456789',
        '48121212121'
    ];

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CiscoGateway;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * ssh login and pass are not set
     * @covers SmsSender\Adapter\FileGateway::send
     * @expectedException \SmsSender\ConfigurationException
     * @expectedExceptionMessage SmsSender\Adapter\CiscoGateway is not configured properly. If SSH is enabled then parameters "ssh_host" and "ssh_login" must be set.
     */
    public function testSendConfigError() {
        $this->object->setParams(['use_ssh' => true]);
        // store_path is not set
        $this->object->send(new \SmsSender\MessageModel);
    }
    
    /**
     * @covers SmsSender\Adapter\CiscoGateway::send
     */
    public function testSend()
    {
        $message = new \SmsSender\MessageModel();
        $message->setText($this->messageText);
        $message->addRecipient('48654123987');
        $result = $this->object->send($message);
        $this->assertTrue($result);
    }
    
    /**
     * @covers SmsSender\Adapter\CiscoGateway::send
     */
    public function testSendSsh()
    {
        $message = new \SmsSender\MessageModel();
        $message->setText($this->messageText);
        $message->addRecipient('48654123987');
        
        $this->object->setParams(['use_ssh' => true]);
        $this->object->setParams(['ssh_login' => 'dummy_user']);
        $this->object->setParams(['ssh_host' => '127.0.0.1']);
        
        $result = $this->object->send($message);
        $this->assertTrue($result);
    }

}
