<?php
namespace SmsSender\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-02 at 10:02:11.
 */
class FileGatewayTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var FileGateway
     */
    protected $object;

    private $messageText = "Message content with ĄŻŹĆŚĘŁÓŃążźćśęłóń";
    
    private $phoneNos = [
        '48123456789',
        '48121212121'
    ];
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new FileGateway();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        foreach ($this->phoneNos as $phone) {
            $file = __DIR__ . DIRECTORY_SEPARATOR . $phone . FileGateway::FILE_EXT;
            if (file_exists($file)) {
                unlink (__DIR__ . DIRECTORY_SEPARATOR . $phone . FileGateway::FILE_EXT);
            }
        }
    }

    /**
     * 
     * @covers SmsSender\Adapter\FileGateway::__construct
     */
    public function testConstructor() {
        $this->object = new FileGateway(['store_path' => __DIR__]);
        $this->assertEquals(__DIR__, $this->object->getParam('store_path'));
    }
    
    /**
     * @covers SmsSender\Adapter\FileGateway::send
     * @expectedException \SmsSender\ConfigurationException
     * @expectedExceptionMessage SmsSender\Adapter\FileGateway is not configured properly. Please set "store_path" parameter.
     */
    public function testSendConfigError() {
        // store_path is not set
        $this->object->send(new \SmsSender\MessageModel);
    }
    
    /**
     * @covers SmsSender\Adapter\FileGateway::send
     */
    public function testSend()
    {
        $this->object->setParams(['store_path' => __DIR__]);
        $message = new \SmsSender\MessageModel();
        $message->setText($this->messageText);
        $message->addRecipient('48123456789');
        $this->assertFileNotExists(__DIR__ . DIRECTORY_SEPARATOR . '48123456789' . \SmsSender\Adapter\FileGateway::FILE_EXT);
        $message->addRecipient('48121212121');
        $this->object->send($message);
        $this->assertFileExists(__DIR__ . DIRECTORY_SEPARATOR . '48123456789' . \SmsSender\Adapter\FileGateway::FILE_EXT);
        $this->assertFileExists(__DIR__ . DIRECTORY_SEPARATOR . '48121212121' . \SmsSender\Adapter\FileGateway::FILE_EXT);
        
        $file = file_get_contents(__DIR__ . DIRECTORY_SEPARATOR . '48123456789' . \SmsSender\Adapter\FileGateway::FILE_EXT);
        $ref = '[48123456789]' . PHP_EOL . $message->getText() . PHP_EOL;
        $this->assertEquals($file, $file);
    }
    
    /**
     * @covers SmsSender\Adapter\FileGateway::setParams
     */
    public function testSetParams() {
        
        $this->object->setParams(['store_path' => __DIR__]);
        $this->assertEquals(__DIR__, $this->object->getParam('store_path'));
        
        $this->expectException(\SmsSender\ConfigurationException::class);
        $this->object->setParams(['dummy' => 1]);
    }
}
