<?php
namespace SmsSender;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-01 at 16:23:24.
 */
class MessageModelTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MessageModel
     */
    protected $object;
    
    private $message = "Message content with ĄŻŹĆŚĘŁÓŃążźćśęłóń";

    private $phones = ['504324567', '48504324431', '504324561', '48000000000'];
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MessageModel;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SmsSender\MessageModel::setText
     */
    public function testSetText()
    {
        $retVal = $this->object->setText($this->message);
        $this->assertEquals($this->message, $retVal->getText());
    }
    
    /**
     * @expectedException InvalidArgumentException
     */
    public function testSetTextEmpty() {
        $this->object->setText('');
    }

    /**
     * @covers SmsSender\MessageModel::getText
     */
    public function testGetText()
    {
        $retVal = $this->object->setText($this->message);
        $this->assertEquals($this->message, $this->object->getText());
    }

    /**
     * @covers SmsSender\MessageModel::addRecipient
     * @expectedException InvalidArgumentException
     */
    public function testAddRecipient()
    {
        $this->object->addRecipient('');
    }
    
    /**
     * @covers SmsSender\MessageModel::getRecipient
     */
    public function testGetRecipient()
    {
        
        $this->addRecipients();
        $retVal = $this->object->getRecipient();
//        foreach ($this->object->getRecipient() as $item) {
//            var_dump ($item);
//        }
        
        foreach ($this->phones as $phone) {
            $this->assertEquals($phone, $retVal->current(), $phone);
            $retVal->next();
        }
    }
    
    /**
     * @covers SmsSender\MessageModel::getRecipients
     */
    public function testGetRecipients() {
        $this->addRecipients();
        $retVal = $this->object->getRecipients();
        $this->assertCount(4, $retVal);
    }
    
    private function addRecipients()
    {
        foreach ($this->phones as $phone) {
            $this->object->addRecipient($phone);            
        }
    }
}
