<?php
namespace SmsSender\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-02 at 09:55:14.
 */
class MockGatewayTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var MockGateway
     */
    protected $object;
    
    protected $message = null;
    
    private $messageText = "Message content with ĄŻŹĆŚĘŁÓŃążźćśęłóń";

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new MockGateway;
        $this->message = new \SmsSender\MessageModel();
        $this->message->setText($this->messageText);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SmsSender\Adapter\MockGateway::send
     */
    public function testSend()
    {
        $this->object->send($this->message);
        $this->object->send($this->message);
        $this->assertCount(2, $this->object->getSentMessages());
    }

    /**
     * @covers SmsSender\Adapter\MockGateway::getSentMessages
     */
    public function testGetSentMessages()
    {
        $this->object->send($this->message);
        $data = $this->object->getSentMessages();
        $this->assertEquals($this->messageText, $data[0]->getText());
    }
}
