<?php
namespace SmsSender\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-02 at 10:02:11.
 */
class SmsApiGatewayTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SmsApiGateway
     */
    protected $object;

    private $messageText = "Message content with ĄŻŹĆŚĘŁÓŃążźćśęłóń";
    
    private $phoneNos = [
        '48123456789',
        '48121212121'
    ];
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SmsApiGateway();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SmsSender\Adapter\SmsApiGateway::send
     * @expectedException \SmsSender\ConfigurationException
     * @expectedExceptionMessage SmsSender\Adapter\SmsApiGateway is not configured properly. Please set "token" or "login" and "passwd_pash" parameters properly.
     */
    public function testTokenConfigError() {
        // store_path is not set
        $this->object->send(new \SmsSender\MessageModel);
    }
    
    
    /**
     * @covers SmsSender\Adapter\SmsApiGateway::send
     * @expectedException \SmsSender\ConfigurationException
     * @expectedExceptionMessage SmsSender\Adapter\SmsApiGateway is not configured properly. Please set "sender" parameter properly.
     */
    public function testSenderConfigError() {
        // store_path is not set
        $this->object->setParams(['token' => 'Vphbs3FT8ALr729JKsGhcmwJ1TGF63Kzivh0HVWS']);
        $this->object->setParams(['sender' => '']);
        $this->object->send(new \SmsSender\MessageModel);
    }
    
    /**
     * @covers SmsSender\Adapter\SmsApiGateway::send
     */
    public function testSend()
    {
        $message = new \SmsSender\MessageModel();
        $message->setText($this->messageText);
        $message->addRecipient('48605171108');
        $this->object->setParams(['token' => 'Vphbs3FT8ALr729JKsGhcmwJ1TGF63Kzivh0HVWS']);
        $result = $this->object->send($message);
        $this->assertTrue($result);
    }
    
    /**
     * @covers SmsSender\Adapter\SmsApiGateway::setParams
     */
    public function testSetParams() {
        
        $this->object->setParams(['token' => 'Vphbs3FT8ALr729JKsGhcmwJ1TGF63Kzivh0HVWS']);
        $this->assertEquals($this->object->getParam('token'), 'Vphbs3FT8ALr729JKsGhcmwJ1TGF63Kzivh0HVWS');
        
        $this->expectException(\SmsSender\ConfigurationException::class);
        $this->object->setParams(['dummy' => 1]);
    }
}
