<?php
namespace SmsSender\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-02 at 10:02:11.
 */
class SmsApiAdapterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SmsApiAdapter
     */
    protected $object;

    private $config = [];
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->config = include  __DIR__ . '/config.php';
        $this->object = new SmsApiAdapter();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SmsSender\Adapter\SmsApiAdapter::send
     * @expectedException \SmsSender\ConfigurationException
     * @expectedExceptionMessage SmsSender\Adapter\SmsApiAdapter is not configured properly. Please set "token" or "login" and "passwd_pash" parameters properly.
     */
    public function testTokenConfigError() {
        // store_path is not set
        $this->object->send(new \SmsSender\MessageModel);
    }
    
    
    /**
     * @covers SmsSender\Adapter\SmsApiAdapter::send
     * @expectedException \SmsSender\ConfigurationException
     * @expectedExceptionMessage SmsSender\Adapter\SmsApiAdapter is not configured properly. Please set "sender" parameter properly.
     */
    public function testSenderConfigError() {
        // store_path is not set
        $this->object->setParams(['token' => $this->config['smsapi_token']]);
        $this->object->setParams(['sender' => '']);
        $this->object->send(new \SmsSender\MessageModel);
    }
    
    /**
     * @covers SmsSender\Adapter\SmsApiAdapter::send
     */
    public function testSend()
    {
        $message = new \SmsSender\MessageModel();
        $message->setText($this->config['message']);
        $message->addRecipient($this->config['my_phone']);
        $this->object->setParams(['token' => $this->config['smsapi_token']]);
        $result = $this->object->send($message);
        $this->assertTrue($result);
        $this->assertCount(0, $this->object->getErrors());
    }
    
    /**
     * @covers SmsSender\Adapter\SmsApiAdapter::setParams
     */
    public function testSetParams() {
        
        $this->object->setParams(['token' => $this->config['smsapi_token']]);
        $this->assertEquals($this->object->getParam('token'), $this->config['smsapi_token']);
        
        $this->expectException(\SmsSender\ConfigurationException::class);
        $this->object->setParams(['dummy' => 1]);
    }
}
