<?php
namespace SmsZilla\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-17 at 00:41:35.
 */
class InfobipAdapterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var InfobipAdapter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->config = include  __DIR__ . '/../../config.php';
        $this->object = new InfobipAdapter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SmsZilla\Adapter\InfobipAdapter::send
     * @todo   Implement testSend().
     */
    public function testSend()
    {
        $message = new \SmsZilla\SmsMessageModel();
        $message->setText($this->config['message']);
        foreach ($this->config['my_phones'] as $no) {
            $message->addRecipient($no);
        }
        $this->object->setParams(['token' => $this->config['infobip_token']]);
        $result = $this->object->send($message);

        $this->assertTrue($result);
        $this->assertCount(0, $this->object->getErrors());
    }
}
