<?php
namespace SmsZilla\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-02 at 10:02:11.
 */
class SerwerSmsAdapterTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SerwerSmsAdapter
     */
    protected $object;

    private $config = [];

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->config = include  __DIR__ . '/../../config.php';
        $this->object = new SerwerSmsAdapter();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SmsZilla\Adapter\SerwerSmsAdapter::send
     * @covers SmsZilla\Adapter\AbstractAdapter::setParams
     * @covers \SmsZilla\ConfigurationException::__construct
     * @expectedException \SmsZilla\ConfigurationException
     * @expectedExceptionMessage SmsZilla\Adapter\SerwerSmsAdapter is not configured properly. Please set "login" and "passwd" parameters properly.
     */
    public function testSenderConfigError() {
        $this->object->setParams(['login' => $this->config['serwersms_login']]);
//        $this->object->setParams(['passwd' => $this->config['serwersms_password']]);
        $this->object->setParams(['sender' => 'serwersms_sender']);
        $this->object->setParams(['extra' => ['test' => $this->config['serwersms_test']]]);
        $this->object->send(new \SmsZilla\SmsMessageModel);
    }

    /**
     * @covers SmsZilla\Adapter\SerwerSmsAdapter::send
     * @covers SmsZilla\Adapter\AbstractAdapter::getErrors
     * @covers \SmsZilla\SendingError::__construct
     */
    public function testSend()
    {
        $message = new \SmsZilla\SmsMessageModel();
        $message->setText($this->config['message']);
        $message->addRecipient($this->config['my_phone']);
        $this->object->setParams([
            'login' => $this->config['serwersms_login'],
            'passwd' => $this->config['serwersms_password'],
            'sender' => $this->config['serwersms_sender'],
            'extra' => ['test' => $this->config['serwersms_test']]
        ]);
        $result = $this->object->send($message);
        $this->assertTrue($result);
        $this->assertCount(0, $this->object->getErrors());
    }

    /**
     * @covers SmsZilla\Adapter\AbstractAdapter::setParams
     */
    public function testSetParams() {

        $this->object->setParams(['login' => $this->config['serwersms_login']]);
        $this->object->setParams(['passwd' => $this->config['serwersms_password']]);
        $this->object->setParams(['extra' => ['utf' => false]]);
        $this->object->setParams(['extra' => ['details' => false]]);
        $this->assertEquals($this->object->getParam('login'), $this->config['serwersms_login']);
        $this->assertEquals($this->object->getParam('passwd'), $this->config['serwersms_password']);
        $extra = $this->object->getParam('extra');
        $this->assertEquals($extra['utf'], false);
        $this->assertEquals($extra['details'], false);

        $this->expectException(\SmsZilla\ConfigurationException::class);
        $this->object->setParams(['dummy' => 1]);
    }
}
