<?php

namespace SmsZilla\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-07 at 22:59:43.
 */
class SmsCenterAdapterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var SmsCenterAdapter
     */
    protected $object;

    private $config = [];
        
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->config = include  __DIR__ . '/../../config.php';
        $this->object = new SmsCenterAdapter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SmsZilla\Adapter\SmsCenterAdapter::send
     * @todo   Implement testSend().
     */
    public function testSend() {
        $message = new \SmsZilla\MessageModel();
        $message->setText($this->config['message']);
        $message->addRecipient($this->config['my_phone']);
        $this->object->setParams(['login' => 'orajo3', 'password' => 'pE4.wU2$kB', 'sender' => '48605171108']);
        $result = $this->object->send($message, false);
        $this->assertTrue($result);
        $this->assertCount(0, $this->object->getErrors());
    }
    
        
    /**
     * @covers SmsZilla\Adapter\SmsCenterAdapter::setParams
     */
    public function testSetParams() {
        $this->object->setParams(['login' => 'orajo', 'password' => 'lS_aP0l', 'sender' => '48605171108']);        
        $this->assertEquals($this->object->getParam('login'), 'orajo');
        
        $this->expectException(\SmsZilla\ConfigurationException::class);
        $this->object->setParams(['dummy' => 1]);
    }

}
