<?php

namespace SmsZilla\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-07 at 22:59:43.
 */
class SmsCenterAdapterTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var SmsCenterAdapter
     */
    protected $object;

    private $config = [];
        
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->config = include  __DIR__ . '/../../config.php';
        $this->object = new SmsCenterAdapter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        
    }

    /**
     * @covers SmsZilla\Adapter\SmsCenterAdapter::send
     */
    public function testSend() {
        $message = new \SmsZilla\SmsMessageModel();
        $message->setText($this->config['message']);
        $message->addRecipient($this->config['my_phone']);
        $this->object->setParams([
            'login' => $this->config['smscenter_login'],
            'password' => $this->config['smscenter_password'],
            'sender' => $this->config['smscenter_sender']]
        );
        $result = $this->object->send($message, false);
        $this->assertTrue($result);
        $this->assertCount(0, $this->object->getErrors());
    }
    
        
    /**
     * @covers SmsZilla\Adapter\SmsCenterAdapter::setParams
     */
    public function testSetParams() {
        $this->object->setParams([
            'login' => $this->config['smscenter_login'],
            'password' => $this->config['smscenter_password'],
            'sender' => $this->config['smscenter_sender']]
        );
        $this->assertEquals($this->object->getParam('login'), $this->config['smscenter_login']);
        
        $this->expectException(\SmsZilla\ConfigurationException::class);
        $this->object->setParams(['dummy' => 1]);
    }

}
