<?php

namespace SmsZilla\Adapter;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-07 at 22:59:43.
 */
class SzybkiSmsAdapterTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var szybkismsAdapter
     */
    protected $object;

    private $config = [];

    /**
     * @covers SmsZilla\Adapter\SzybkiSmsAdapter::send
     */
    public function testSend()
    {
        $message = new \SmsZilla\SmsMessageModel();
        $message->setText($this->config['message']);
        $message->addRecipient($this->config['my_phone']);
        $this->object->setParams([
                'token' => $this->config['szybkisms_token'],
                'sender' => $this->config['szybkisms_sender']]
        );
        $result = $this->object->send($message, false);
        $this->assertTrue($result);
        $this->assertCount(0, $this->object->getErrors());
    }

    /**
     * @covers SmsZilla\Adapter\SzybkiSmsAdapter::setParams
     */
    public function testSetParams()
    {
        $this->object->setParams([
                'token' => $this->config['szybkisms_token'],
                'sender' => $this->config['szybkisms_sender']]
        );
        $this->assertEquals($this->object->getParam('token'), $this->config['szybkisms_token']);

        $this->expectException(\SmsZilla\ConfigurationException::class);
        $this->object->setParams(['dummy' => 1]);
    }

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->config = include __DIR__ . '/../../config.php';
        $this->object = new SzybkiSmsAdapter();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {

    }

}
