<?php
namespace SmsZilla;

include __DIR__ . '/Validator/DummyValidator.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-02 at 10:25:21.
 */
class SmsSenderTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var SmsZilla
     */
    protected $object;

    protected $config;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->config = include  __DIR__ . '/../config.php';
        $this->object = new SmsSender(new \SmsZilla\Adapter\MockAdapter());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \SmsZilla\SmsSender::__construct
     */
    public function testConstructor() {
        $result = new SmsSender(new \SmsZilla\Adapter\MockAdapter(), []);
        $this->assertEquals($this->object, $result);
    }

    /**
     * @covers \SmsZilla\SmsSender::__construct
     */
    public function testConstructorParams() {
        $reference = new \SmsZilla\Adapter\FileAdapter(['store_path' => __DIR__]);
        $result = new SmsSender(new \SmsZilla\Adapter\FileAdapter(), ['store_path' => __DIR__]);
        $this->assertEquals($reference, $result->getAdapter());
    }

    /**
     * @covers SmsZilla\SmsSender::setText
     * @expectedException \InvalidArgumentException
     */
    public function testSetTextError()
    {
        $retVal = $this->object->setText('');
        $this->assertEquals($this->config['message'], $retVal->getText());
    }

    /**
     * @covers SmsZilla\SmsSender::setText
     */
    public function testSetText()
    {
        $retVal = $this->object->setText($this->config['message']);
        $this->assertEquals($this->config['message'], $retVal->getText());
    }

    /**
     * @covers SmsZilla\SmsSender::getText
     */
    public function testGetText()
    {
        $retVal = $this->object->setText($this->config['message']);
        $this->assertEquals($this->config['message'], $retVal->getText());
    }

    /**
     * @covers SmsZilla\SmsSender::setMessage
     * @covers SmsZilla\SmsMessageModel::setText
     */
    public function testSetMessage()
    {
        $message = new SmsMessageModel();
        $message->setText($this->config['message']);
        $this->object->setMessage($message);
        $this->assertAttributeEquals($this->config['message'], 'text', $message);
    }

    /**
     * @covers SmsZilla\SmsSender::getMessage
     */
    public function testGetMessage()
    {
        $this->assertInstanceOf(SmsMessageModel::class, $this->object->getMessage());
        $message = new SmsMessageModel();
        $message->setText($this->config['message']);
        $message->addRecipient('654789321');
        $testMsg = clone $message;
        $this->object->setMessage($message);
        $this->assertEquals($testMsg, $this->object->getMessage());
    }

    /**
     * @covers SmsZilla\SmsSender::setRecipient
     * @covers SmsZilla\SmsSender::getRecipients
     * @covers SmsZilla\SmsSender::setValidator
     */
    public function testSetRecipientNoValidation()
    {
        $this->object->setValidator(new \DummyValidator());
        $this->object->setRecipient('654789321');
        $this->object->setRecipient('48147258369');
        $textVal = $this->object->getRecipients();
        $expected = array('654789321', '48147258369');
        $this->assertEquals($expected, $textVal);
    }

    /**
     * @covers SmsZilla\SmsSender::getRecipients
     * @covers SmsZilla\SmsSender::setRecipient
     */
    public function testGetRecipients()
    {
        $this->object->setValidator(new Validator\LibphonenumberValidator('PL'));
        $phones = ['504324567', '48504324431', '504324561', '480000000'];
        $phonesExpected = ['48504324567', '48504324431', '48504324561'];
        $this->object->setRecipient($phones);
        $testVal = $this->object->getRecipients();
        $this->assertEquals($phonesExpected, $testVal);
    }

    /**
     * @covers SmsZilla\SmsSender::send
     * @covers SmsZilla\Adapter\MockAdapter::getSentMessages
     */
    public function testSend()
    {
        $message = new SmsMessageModel();
        $message->setText($this->config['message']);
        $this->object->setMessage($message);
        $result = $this->object->send();
        $this->assertTrue($result);
        $messages = $this->object->getAdapter()->getSentMessages();
        $this->assertCount(1, $messages);

        $this->assertEquals($message, $messages[0]);
    }

    /**
     * @covers SmsZilla\SmsSender::send
     * @covers SmsZilla\Adapter\MockAdapter::getSentMessages
     */
    public function testSend2()
    {
        $this->object->setRecipient('695687123');
        $this->object->setText($this->config['message']);
        $result = $this->object->send();
        $this->assertTrue($result);
    }


    /**
     * @covers SmsZilla\SmsSender::getAdapter
     */
    public function testGetAdapter()
    {
        $expected = new \SmsZilla\Adapter\MockAdapter();
        $result = $this->object->getAdapter();
        $this->assertEquals($expected, $result);
    }

    /**
     * @covers \SmsZilla\SmsSender::getRecipients
     * @covers \SmsZilla\SmsSender::setRecipient
     * @covers \SmsZilla\SmsSender::setValidator
     */
    public function testValidation() {
        $this->object->setValidator(new Validator\LibphonenumberValidator('PL'));
        $this->object->setRecipient('695687123', false);
        $result = $this->object->getRecipients();
        $this->assertEquals('48695687123', $result[0]);

        // testing parsing phone number using defferent region
        $this->object->setValidator(new Validator\LibphonenumberValidator('CH'));
        $this->object->setRecipient('41758180020', false);
        $this->object->setRecipient('758185021', false);
        $this->object->setRecipient('+48605874569', false);
        $result = $this->object->getRecipients();

        $this->assertEquals('41758180020', $result[1]);
        $this->assertEquals('41758185021', $result[2]);
        $this->assertEquals('48605874569', $result[3]);
    }

}
